# frozen_string_literal: true

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: proto/helloworld.proto for package 'sample'

require 'grpc'
require './proto/helloworld_pb'

module Sample
  module Greeter
    # The greeting service definition.
    # gRPCのサービス
    class Service
      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'sample.Greeter'

      # Sends a greeting
      # 実装されるRPC
      rpc :SayHello, HelloRequest, HelloReply
    end

    Stub = Service.rpc_stub_class
  end
end
