# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/helloworld.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("proto/helloworld.proto", :syntax => :proto3) do
    add_message "sample.HelloRequest" do
      optional :first_name, :string, 1
      optional :last_name, :string, 2
    end
    add_message "sample.HelloReply" do
      optional :message, :string, 1
    end
  end
end

module Sample
  HelloRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("sample.HelloRequest").msgclass
  HelloReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("sample.HelloReply").msgclass
end
