# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/notification.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("proto/notification.proto", :syntax => :proto3) do
    add_message "sample.PereodicHelloRequest" do
      optional :first_name, :string, 1
      optional :last_name, :string, 2
    end
    add_message "sample.PeriodicHelloReply" do
      optional :message, :string, 1
    end
  end
end

module Sample
  PereodicHelloRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("sample.PereodicHelloRequest").msgclass
  PeriodicHelloReply = Google::Protobuf::DescriptorPool.generated_pool.lookup("sample.PeriodicHelloReply").msgclass
end
